package com.cqvip.edures.db;

import java.util.Date;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SEARCH_HISTORY.
 */
public class SearchHistory {

    private Long id;
    private String historyword;
    private java.util.Date date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SearchHistory() {
    }

    public SearchHistory(Long id) {
        this.id = id;
    }

    public SearchHistory(Long id, String historyword, java.util.Date date) {
        this.id = id;
        this.historyword = historyword;
        this.date = date;
    }
    // KEEP METHODS - put your custom methods here
    public SearchHistory(String historyword) {
        this.historyword = historyword;
        this.date =new Date();
    }
    // KEEP METHODS END


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHistoryword() {
        return historyword;
    }

    public void setHistoryword(String historyword) {
        this.historyword = historyword;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
